### ISSUE TITLE
Debuggin TypeScript + SystemJS

### ISSUE THREAD

**Issue by tfrydrychewicz** [Microsoft/vscode-webkit-debug#41]
I've a project with TS + SystemJS. The structure is,

- project-folder
    - index.html
    - wwwroot
       - app
           - ...TS sources
       - dist
            - app
                - ...compiled js with sourcemaps embedded (with soureRoot set to /wwwroot/app)

I'd like to debug it with chrome attach, but I cannot figure out proper launch.json config. How can I debug such structure?

**Comment by roblourens** [comment]
Is `index.html` under `wwwroot` somewhere? Or does it have script references like `src="wwwroot/dist/app/file.js"`?

This is a start but may not be quite right -
```
{
    "version": "0.1.0",
    "configurations": [
        {
            "name": "attach to chrome",
            "type": "chrome",
            "port": 9222,
            "request": "attach",
            "sourceMaps": true,
            "outDir": "wwwroot/dist"
        },
        {
            "name": "launch chrome",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost/index.html",
            "sourceMaps": true,
            "outDir": "wwwroot/dist"
        }
    ]
}

```

**Comment by tfrydrychewicz** [comment]
Unfortunately, that doesn't work. I've created a small scaffold which should reflect our project structure. It's available [here](https://github.com/tfrydrychewicz/vscode-chrome-debugger-with-ts-and-systemjs). Could you please help me with setting up your debugger to work with such project.

Thanks! :)

**Comment by roblourens** [comment]
Created [a PR](https://github.com/tfrydrychewicz/vscode-chrome-debugger-with-ts-and-systemjs/pull/1). Basically two issues:

•You need to set "cwd" to the web root - I need better docs for this!
•Since the extension reads sourcemaps off the disk,  sourceRoot  needs to be a relative path or absolute local path, so '/app' won't work right now. Changing it to an absolute path set at build time to unblock you. This kind of goes along with #40 so I think it might work when I fix that.

With this change I can hit the breakpoint and debug.

**Comment by tfrydrychewicz** [comment]
Works awesome! Thanks a lot :)
